test: use linuxdeepin pr 61 test doc check
deepin-community/dtkcore pull request #1
Opened 2022-07-21 08:03 UTC by tsic404

use linuxdeepin/dtkcore pr 61 test doc check

2022-07-21 08:18 UTC, tsic404 commented
recheck

2022-07-21 08:32 UTC, tsic404 commented
recheck

2022-07-21 08:35 UTC, tsic404 commented
recheck

2022-07-21 08:41 UTC, tsic404 commented
recheck

2022-07-21 08:52 UTC, tsic404 commented
recheck

2022-07-21 09:41 UTC, tsic404 commented
recheck

2022-07-21 09:48 UTC, tsic404 commented
recheck

2022-07-21 10:00 UTC, tsic404 commented
recheck

2022-07-21 11:16 UTC, tsic404 commented
recheck

2022-07-21 13:42 UTC, tsic404 commented
recheck

2022-07-21 13:54 UTC, tsic404 commented
recheck

2022-07-21 14:01 UTC, tsic404 commented
recheck

2022-07-21 14:11 UTC, tsic404 commented
recheck

2022-07-21 14:18 UTC, tsic404 commented
recheck

2022-07-21 14:45 UTC, tsic404 commented
recheck

2022-07-21 14:52 UTC, tsic404 commented
recheck

2022-07-21 15:00 UTC, tsic404 commented
recheck

2022-07-21 15:12 UTC, tsic404 commented
recheck

2022-07-21 15:21 UTC, tsic404 commented
recheck

2022-07-25 06:32 UTC, tsic404 commented
rehceck

2022-07-25 06:43 UTC, tsic404 commented
recheck

2022-07-25 09:46 UTC, tsic404 commented
recheck

2022-07-25 10:03 UTC, tsic404 commented
recheck

2022-07-25 10:10 UTC, tsic404 commented
recheck

2022-07-25 10:11 UTC, tsic404 commented
recheck

2022-07-26 08:51 UTC, tsic404 commented
recheck

2022-07-26 08:58 UTC, tsic404 commented
recheck

2022-07-26 09:09 UTC, tsic404 commented
recheck

2022-07-26 09:24 UTC, tsic404 commented
recheck

2022-07-26 09:35 UTC, tsic404 commented
recheck

2022-07-26 09:44 UTC, tsic404 commented
recheck

2022-07-26 09:56 UTC, tsic404 commented
recheck

2022-07-26 10:47 UTC, tsic404 commented
recheck

2022-07-26 10:58 UTC, tsic404 commented
recheck

2022-07-26 11:05 UTC, tsic404 commented
recheck

2022-07-26 11:15 UTC, tsic404 commented
recheck

2022-07-26 11:22 UTC, tsic404 commented
recheck

2022-07-26 12:27 UTC, Zeno-sole requested changes
This is close to perfect! Please address the suggested inline change.

2022-07-26 12:28 UTC, Zeno-sole requested changes
This is close to perfect! Please address the suggested inline change.

2022-07-26 12:29 UTC, Zeno-sole requested changes
Here is the body for the review.

2022-07-26 12:30 UTC, Zeno-sole requested changes
Here is the body for the review.

2022-07-26 12:30 UTC, Zeno-sole requested changes
Here is the body for the review.

2022-07-26 12:45 UTC, Zeno-sole reviewed
This is close to perfect! Please address the suggested inline change.

2022-07-26 12:45 UTC, Zeno-sole reviewed
This is close to perfect! Please address the suggested inline change.

2022-07-26 12:54 UTC, Zeno-sole reviewed
This is close to perfect! Please address the suggested inline change.

2022-07-26 12:54 UTC, Zeno-sole commented on src/log/CuteLogger_global.h
test

2022-07-26 12:56 UTC, Zeno-sole reviewed
This is close to perfect! Please address the suggested inline change.

2022-07-26 12:56 UTC, Zeno-sole commented on src/log/CuteLogger_global.h
> +#ifndef CUTELOGGER_DEFAULT_LOG_FORMAT
define CUTELOGGER_DEFAULT_LOG_FORMAT is not documented!

2022-07-26 13:01 UTC, Zeno-sole reviewed
This is close to perfect! Please address the suggested inline change.

2022-07-26 13:01 UTC, Zeno-sole commented on src/log/CuteLogger_global.h
> +#define CUTELOGGER_DEFAULT_LOG_FORMAT QLatin1String("%{time}{yyyy-MM-dd, HH:mm:ss.zzz} [%{type:-7}] [%{file:-20} %{function:-35} %{line}] %{message}\n")
define CUTELOGGER_DEFAULT_LOG_FORMAT is not documented!

2022-07-26 13:19 UTC, Zeno-sole reviewed
All has documented well!

2022-07-26 13:26 UTC, Zeno-sole reviewed
All has documented well!

2022-07-26 13:30 UTC, tsic404 commented
recheck

2022-07-26 13:31 UTC, tsic404 commented
recheck

2022-07-27 01:23 UTC, tsic404 commented
recheck

2022-07-27 01:34 UTC, tsic404 commented
recheck

2022-07-27 01:40 UTC, Zeno-sole reviewed
All has documented well!

2022-07-27 01:47 UTC, tsic404 commented
recheck

2022-07-27 01:52 UTC, Zeno-sole reviewed
All has documented well!

2022-07-27 02:04 UTC, tsic404 commented
recheck

2022-07-27 02:08 UTC, Zeno-sole reviewed
All has documented well!

2022-07-27 02:10 UTC, tsic404 commented
recheck

2022-07-27 02:15 UTC, Zeno-sole reviewed
All has documented well!

2022-07-27 02:20 UTC, Zeno-sole reviewed
All has documented well!

2022-07-27 02:22 UTC, Zeno-sole reviewed
All has documented well!

2022-07-27 02:23 UTC, Zeno-sole reviewed
All has documented well!

2022-07-27 02:25 UTC, Zeno-sole reviewed
All has documented well!

2022-07-27 02:25 UTC, Zeno-sole requested changes
There is still something that need to be documented!

2022-07-27 02:25 UTC, Zeno-sole commented on src/log/CuteLogger_global.h
> +#define CUTELOGGER_DEFAULT_LOG_FORMAT QLatin1String("%{time}{yyyy-MM-dd, HH:mm:ss.zzz} [%{type:-7}] [%{file:-20} %{function:-35} %{line}] %{message}\n")
define CUTELOGGER_DEFAULT_LOG_FORMAT is not documented!

2022-07-27 02:27 UTC, Zeno-sole requested changes
There is still something that need to be documented!

2022-07-27 02:27 UTC, Zeno-sole commented on src/log/CuteLogger_global.h
> +#define CUTELOGGER_DEFAULT_LOG_FORMAT QLatin1String("%{time}{yyyy-MM-dd, HH:mm:ss.zzz} [%{type:-7}] [%{file:-20} %{function:-35} %{line}] %{message}\n")
define CUTELOGGER_DEFAULT_LOG_FORMAT is not documented!

2022-07-27 02:28 UTC, tsic404 commented
recheck

2022-07-27 02:33 UTC, Zeno-sole reviewed
All has documented well!

2022-07-27 02:35 UTC, tsic404 commented
recheck

2022-07-27 02:39 UTC, Zeno-sole reviewed
All has documented well!

2022-07-27 02:42 UTC, tsic404 commented
recheck

2022-07-27 02:47 UTC, Zeno-sole reviewed
All has documented well!

2022-07-27 02:55 UTC, tsic404 commented
recheck

2022-07-27 03:00 UTC, Zeno-sole reviewed
You're A Good Friend!

2022-07-27 03:04 UTC, tsic404 commented
recheck

2022-07-27 03:08 UTC, Zeno-sole reviewed
You're So Kind!

2022-07-27 03:27 UTC, Zeno-sole reviewed
Great Answer!

2022-07-27 04:43 UTC, Zeno-sole reviewed
You're Sharp!

2022-07-27 04:43 UTC, Zeno-sole reviewed
You Made It Happen!

2022-07-27 04:44 UTC, Zeno-sole reviewed
You're Super!

2022-07-27 04:44 UTC, Zeno-sole reviewed
You're A Good Friend!

2022-07-27 04:47 UTC, Zeno-sole reviewed
You're A Champ!

2022-07-27 04:47 UTC, Zeno-sole reviewed
You're A Shining Star!

2022-07-27 04:47 UTC, Zeno-sole requested changes
There is still something that need to be documented!

2022-07-27 04:47 UTC, Zeno-sole commented on src/log/CuteLogger_global.h
> +#ifndef CUTELOGGER_DEFAULT_LOG_FORMAT
define CUTELOGGER_DEFAULT_LOG_FORMAT is not documented!

2022-07-27 04:48 UTC, Zeno-sole requested changes
There is still something that need to be documented!

2022-07-27 04:48 UTC, Zeno-sole commented on src/log/CuteLogger_global.h
> +#define CUTELOGGER_DEFAULT_LOG_FORMAT QLatin1String("%{time}{yyyy-MM-dd, HH:mm:ss.zzz} [%{type:-7}] [%{file:-20} %{function:-35} %{line}] %{message}\n")
define CUTELOGGER_DEFAULT_LOG_FORMAT is not documented!

2022-07-27 04:51 UTC, Zeno-sole requested changes
There is still something that need to be documented, Come on it!

2022-07-27 04:51 UTC, Zeno-sole commented on src/log/CuteLogger_global.h
> +#define CUTELOGGER_DEFAULT_LOG_FORMAT QLatin1String("%{time}{yyyy-MM-dd, HH:mm:ss.zzz} [%{type:-7}] [%{file:-20} %{function:-35} %{line}] %{message}\n")
define CUTELOGGER_DEFAULT_LOG_FORMAT is not documented!

2022-07-27 05:23 UTC, tsic404 commented
recheck

2022-07-27 05:27 UTC, Zeno-sole reviewed
You're An Angel!

2022-07-27 05:40 UTC, tsic404 commented
recheck

2022-07-27 05:49 UTC, Zeno-sole reviewed
5 Star Work!

2022-07-27 05:58 UTC, tsic404 commented
reche

2022-07-27 05:58 UTC, closed without merging